/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AlarmEvent = IDL.Record({
  'childProfileId' : IDL.Text,
  'acknowledged' : IDL.Bool,
  'timestamp' : Time,
});
export const BiometricRecord = IDL.Record({
  'id' : IDL.Nat,
  'data' : IDL.Vec(IDL.Nat8),
  'childId' : IDL.Text,
  'dataType' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ChildProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isArchived' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlarm' : IDL.Func([], [], []),
  'addBiometricRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'archiveChildProfile' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChildProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteBiometricRecord' : IDL.Func([IDL.Nat], [], []),
  'getAlarmEvents' : IDL.Func([], [IDL.Vec(AlarmEvent)], ['query']),
  'getBiometricRecordsForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BiometricRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChildProfiles' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
  'getLinkedChildProfile' : IDL.Func([], [IDL.Opt(ChildProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAlarmActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkPrincipalToChild' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'renameChildProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGuardianPin' : IDL.Func([IDL.Text], [], []),
  'triggerAlarm' : IDL.Func([], [], []),
  'unlinkPrincipalFromChild' : IDL.Func([IDL.Principal], [], []),
  'verifyGuardianPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AlarmEvent = IDL.Record({
    'childProfileId' : IDL.Text,
    'acknowledged' : IDL.Bool,
    'timestamp' : Time,
  });
  const BiometricRecord = IDL.Record({
    'id' : IDL.Nat,
    'data' : IDL.Vec(IDL.Nat8),
    'childId' : IDL.Text,
    'dataType' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ChildProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isArchived' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlarm' : IDL.Func([], [], []),
    'addBiometricRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'archiveChildProfile' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChildProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteBiometricRecord' : IDL.Func([IDL.Nat], [], []),
    'getAlarmEvents' : IDL.Func([], [IDL.Vec(AlarmEvent)], ['query']),
    'getBiometricRecordsForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BiometricRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChildProfiles' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
    'getLinkedChildProfile' : IDL.Func([], [IDL.Opt(ChildProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAlarmActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkPrincipalToChild' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'renameChildProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGuardianPin' : IDL.Func([IDL.Text], [], []),
    'triggerAlarm' : IDL.Func([], [], []),
    'unlinkPrincipalFromChild' : IDL.Func([IDL.Principal], [], []),
    'verifyGuardianPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };