/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlarmEvent {
  'childProfileId' : string,
  'acknowledged' : boolean,
  'timestamp' : Time,
}
export interface BiometricRecord {
  'id' : bigint,
  'data' : Uint8Array,
  'childId' : string,
  'dataType' : string,
  'timestamp' : Time,
}
export interface ChildProfile {
  'id' : string,
  'name' : string,
  'isArchived' : boolean,
}
export interface RecordListEntry {
  'id' : bigint,
  'recordType' : { 'touch' : null } |
    { 'biometric' : null },
  'childId' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface TouchRecord {
  'id' : bigint,
  'childId' : string,
  'recordTimestamp' : Time,
  'samples' : Array<TouchSample>,
}
export interface TouchSample {
  'x' : number,
  'y' : number,
  'force' : number,
  'radiusX' : number,
  'radiusY' : number,
  'rotationAngle' : number,
  'timestamp' : Time,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlarm' : ActorMethod<[], undefined>,
  'addBiometricRecord' : ActorMethod<[string, string, Uint8Array], bigint>,
  'addTouchRecord' : ActorMethod<[string, Array<TouchSample>], bigint>,
  'archiveChildProfile' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChildProfile' : ActorMethod<[string, string], undefined>,
  'deleteBiometricRecord' : ActorMethod<[bigint], undefined>,
  'deleteTouchRecord' : ActorMethod<[bigint], undefined>,
  'getAlarmEvents' : ActorMethod<[], Array<AlarmEvent>>,
  'getBiometricRecordsForChild' : ActorMethod<[string], Array<BiometricRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChildProfiles' : ActorMethod<[], Array<ChildProfile>>,
  'getLinkedChildProfile' : ActorMethod<[], [] | [ChildProfile]>,
  'getTouchRecordsForChild' : ActorMethod<[string], Array<TouchRecord>>,
  'getUnifiedRecordList' : ActorMethod<[], Array<RecordListEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAlarmActive' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkPrincipalToChild' : ActorMethod<[Principal, string], undefined>,
  'renameChildProfile' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGuardianPin' : ActorMethod<[string], undefined>,
  'triggerAlarm' : ActorMethod<[], undefined>,
  'unlinkPrincipalFromChild' : ActorMethod<[Principal], undefined>,
  'verifyGuardianPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];